[".local/share/zsh-snap"]
type  = "git-repo"
url   = "https://github.com/marlonrichert/zsh-snap.git"
exact = true
refreshPeriod = "168h" # once a week

[".local/share/zsh/site-functions/_pip"]
type  = "file"
url   = "https://gist.github.com/blueyed/54a257c411310a28805a/raw/_pip.zsh"
refreshPeriod = "168h" # once a week
