- name: Install Dotfiles
  hosts: dotfiles
  gather_facts: yes
  gather_subset: hardware
  roles:
    - {role: git, tags: git}
    - {role: nano, tags: nano}
    - {role: python, tags: python}
    - {role: ssh, tags: ssh}
    - {role: zsh, tags: zsh}
    - role: finder
      tags: finder
      when: ansible_distribution == "MacOSX"
    - role: macos
      tags: macos
      when: ansible_distribution == "MacOSX"
