- name: Install Dotfiles
  hosts: dotfiles
  gather_facts: True
  gather_subset: hardware
  vars_files:
    - vars/config.yml
  roles:
    - {role: git, tags: git}
    - {role: nano, tags: nano}
    - {role: python, tags: python}
