- name: Install Dotfiles
  hosts: dotfiles
  gather_facts: yes
  gather_subset: hardware
  vars_files:
    - vars/config.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/bin"
  roles:
    - {role: ssh, tags: ssh}
    - {role: zsh, tags: zsh}
    - {role: git, tags: git}
    - {role: nano, tags: nano}
    - {role: python, tags: python}
    - role: macos
      tags: macos
      when: distribution == "MacOSX"
