- name: Install Applications
  hosts: setup
  tags: [never, install]
  gather_facts: yes
  gather_subset: hardware
  vars_files:
    - vars/config.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/bin"
  roles:
    - role: homebrew
      tags: [homebrew, packages]
      when: distribution == "MacOSX"
    - role: apt
      tags: [apt, packages]
      when: distribution == "Ubuntu"
    - role: opkg
      tags: [opkg, packages]
      when: distribution == "DSM"

- name: Install Dotfiles
  hosts: dotfiles
  gather_facts: yes
  gather_subset: hardware
  vars_files:
    - vars/config.yml
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/bin"
  roles:
    - {role: git, tags: git}
    - {role: nano, tags: nano}
    - {role: python, tags: python}
    - {role: ssh, tags: ssh}
    - {role: docker, tags: docker}
    - {role: zsh, tags: zsh}
    - role: macos
      tags: macos
      when: distribution == "MacOSX"
