# See https://github.com/hashicorp/terraform-mcp-server
[Terraform.config]
enabled = true
command = "docker"
args = ["run", "-i", "--rm", "hashicorp/terraform-mcp-server", "--toolsets=registry"]

[Terraform.tools]
# Providers
search_providers = "allow"
get_provider_details = "allow"
get_provider_capabilities = "allow"
get_latest_provider_version = "allow"
# Modules
search_modules = false
get_module_details = false
get_latest_module_version = false
# Policies
search_policies = false
get_policy_details = false
