- name: Make sure that we run on macOS
  assert: { that: ansible_distribution == "MacOSX" }

- name: Set User defaults
  import_tasks: user-defaults.yml

- name: Set System defaults
  import_tasks: system-defaults.yml
  when:
    - not macos.skip_system|bool
