- name: Closing any system preferences to prevent issues with automated changes
  command: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

# This is not technically required. However the error messages are otherwise
# lost when capturing the output so we include this extra step to give a
# understandable error message if we cannot escalate privileges.
#
# Also the meta module has a noop operation which does not support conditionals.
# As a workaround we use the shell module to perform a noop.
- name: Validate that sudo access is possible
  become: true
  command: "true"
  changed_when: false

##############################################################################
# Configuring the Computer Name
##############################################################################
- name: Set computer name (as done via System Preferences → Sharing)
  when: macos.computer_name
  become: true
  block:
    - name: Set the computer name
      systemsetup:
        setting: computername
        value: "{{ macos.computer_name }}"

    - name: Set the host name
      shell: |
        old=$(scutil --get HostName)
        scutil --set HostName "{{ macos.computer_name }}"
        if [ "$(scutil --get HostName)" = "$old" ]; then
          echo "Unchanged"
        fi
      register: result
      changed_when: result.stdout != "Unchanged"

    - name: Set NetBIOS name
      osx_defaults:
        domain: /Library/Preferences/SystemConfiguration/com.apple.smb.server
        key: NetBIOSName
        value: "{{ macos.computer_name }}"
      when: "'MacBook'|lower not in macos.computer_name|lower"

##############################################################################
# Configuring Security Settings
##############################################################################
- name: Disable remote apple events
  become: true
  command: systemsetup -setremoteappleevents {{ macos.remote_apple_events|onoff }}
  register: result
  changed_when: "result.stdout == 'setremoteappleevents: ' ~ macos.remote_apple_events|onoff"
  when: macos.remote_apple_events is not none

- name: Disable remote login
  become: true
  command: systemsetup -f -setremotelogin {{ macos.remote_login|onoff }}
  register: result
  changed_when: result.stdout|length > 0
  when: macos.remote_login is not none

##############################################################################
# Configuring System Settings
##############################################################################
- name: Disable guest account login
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: GuestEnabled
    type: bool
    value: "{{ macos.guest_account_login }}"
  when: macos.guest_account_login is not none

- name:
    Reveal IP address, hostname, OS version, etc. when clicking the clock in the
    login window
  become: true
  osx_defaults:
    domain: /Library/Preferences/com.apple.loginwindow
    key: AdminHostInfo
    value: HostName
    state: "{{ macos.login_window_host_info | ternary('present', 'absent') }}"
  when: macos.login_window_host_info is not none

- name: Restart automatically if the computer freezes
  become: true
  systemsetup:
    setting: restartfreeze
    value: "{{ macos.restart_after_freeze }}"
  when: macos.restart_after_freeze is not none

- name: Set computer sleep delay
  become: true
  systemsetup:
    setting: computersleep
    value: "{{ macos.computer_sleep }}"
  when: macos.computer_sleep is not none

- name: Set Display sleep delay
  become: true
  systemsetup:
    setting: displaysleep
    value: "{{ macos.display_sleep }}"
  when: macos.display_sleep is not none
