- name: Check existing SSH key
  stat:
    path: "{{ ssh.key }}"
  register: result
  when: ssh.key is not none

- name: Generate SSH Key
  command:
    cmd: ssh-keygen -o -a 100 -t ed25519 -f {{ ssh.key | quote }} -N {{ ssh.key_passphrase | quote }}
    creates: "{{ ssh.key }}"
  when:
    - not result.stat.exists
    - ssh.key is not none

- name: Add GitHub SSH Keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: https://github.com/{{ github_user }}.keys
    comment: "{{ ssh.github_keys_comment or omit }}"
  when: ssh.github_keys

- name: Add SSH Keys
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item.key if item is mapping else item }}"
    comment: "{{ item.comment if item is mapping else omit }}"
  with_items: "{{ ssh.authorized_keys }}"

- name: Generate SSH Config
  template:
    src: config.j2
    dest: ~/.ssh/config
