---
- name: Install Antibody via Homebrew
  homebrew:
    name: getantibody/tap/antibody
    state: present
  when:
    - ansible_distribution == "MacOSX"
    - zsh.antibody != "manual"

- name: Install Antibody
  become: "{{ zsh.antibody_system_install }}"
  shell:
    cmd: curl -sfL git.io/antibody | sh -s - -b {{ antibody_path }}
    creates: "{{ antibody_path }}/antibody"
    warn: false
  vars:
    antibody_default_path: '{{ zsh.antibody_system_install | bool | ternary("/usr/local/bin", "~/.local/bin") }}'
    antibody_path: '{{ zsh.antibody_path or antibody_default_path }}'
  when:
    - ansible_distribution != "MacOSX" or zsh.antibody == "manual"
