---
- name: Install Antibody via Homebrew
  homebrew:
    name: getantibody/tap/antibody
    state: present
  when:
    - distribution == "MacOSX"
    - zsh.antibody != "manual"

- name: Install Antibody
  become: "{{ zsh.antibody_system_install }}"
  shell: curl -sfL git.io/antibody | sh -s - -b {{ antibody_path }}
  args:
    warn: false
    creates: "{{ antibody_path }}/antibody"
  vars:
    antibody_default_path: '{{ "/usr/local/bin" if zsh.antibody_system_install|bool else "~/.local/bin" }}'
    antibody_path: '{{ zsh.antibody_path | default(antibody_default_path) }}'
  when:
    - distribution != "MacOSX" or zsh.antibody == "manual"
    - not zsh.antibody_system_install|bool or sudo|bool
