- name: Finding ZSH
  shell: command -v zsh
  changed_when: false
  register: zsh_command
  when: not zsh.location

- name: Check for ZSH in /etc/shells
  command: grep -Fxq {{ zsh.location or zsh_command.stdout }} /etc/shells
  register: zsh_in_shells
  check_mode: false
  failed_when: false
  changed_when: false
  when:
    - zsh_command.rc == 0 or zsh.location

- name: Add ZSH to /etc/shells
  become: true
  lineinfile:
    line: "{{ zsh.location or zsh_command.stdout }}"
    dest: /etc/shells
    state: present
  when:
    - zsh_in_shells.rc != 0
    - zsh_command.rc == 0 or zsh.location

- name: Set the default shell to ZSH
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh.location or zsh_command.stdout }}"
  when:
    - zsh.default
    - zsh_command.rc == 0 or zsh.location
    - not zsh.shell_exec
  
- name: Set the exec shell to ZSH
  template:
    src: underpriviliged-profile.j2
    dest: "{% if zsh.shell_exec is sameas true %}~/.profile{% else %}{{ zsh.shell_exec }}{% endif %}"
  when: zsh.shell_exec
