- name: Make sure that we run on macOS
  assert: { that: ansible_distribution == "MacOSX" }

- name: Configure Format for New Documents
  osx_defaults:
    domain: com.apple.TextEdit
    key: RichText
    type: int
    value: "{{ textedit.rich_text | ternary (1, 0) }}"
  notify: Quit TextEdit
  when: textedit.rich_text is not none

- name: Configure UTF-8 when Loading Documents
  osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncoding
    type: int
    value: 4
    state: "{{ textedit.utf8 | ternary ('present', 'absent') }}"
  notify: Quit TextEdit
  when: textedit.utf8 is not none

- name: Configure UTF-8 when Saving Documents
  osx_defaults:
    domain: com.apple.TextEdit
    key: PlainTextEncodingForWrite
    type: int
    value: 4
    state: "{{ textedit.utf8 | ternary ('present', 'absent') }}"
  notify: Quit TextEdit
  when: textedit.utf8 is not none
