- name: Create docker-compose Directory
  file:
    path: "{{ _compose_dir }}"
    state: directory

- name: Install docker-compose
  get_url:
    url: "{{ _compose_url }}"
    dest: "{{ _compose_dir }}/docker-compose"
    mode: 0755
    force: yes
