name: Lint
on: [push, pull_request]

jobs:
  lint:
    name: Lint Dotfiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: dotfiles.yml
          args: -q -p
